In [1]:
import pandas as pd

In [3]:
dataset=pd.read_csv("auto-mpg.csv")

In [4]:
dataset

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198.0,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199.0,97,2774,15.5,70,1,amc hornet
17,21.0,6,200.0,85,2587,16.0,70,1,ford maverick
18,27.0,4,97.0,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104.0,95,2375,17.5,70,2,saab 99e
23,26.0,4,121.0,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199.0,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97.0,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27.0,4,112.0,88,2640,18.6,82,1,chevrolet cavalier wagon
369,34.0,4,112.0,88,2395,18.0,82,1,chevrolet cavalier 2-door
370,31.0,4,112.0,85,2575,16.2,82,1,pontiac j2000 se hatchback
371,29.0,4,135.0,84,2525,16.0,82,1,dodge aries se
372,27.0,4,151.0,90,2735,18.0,82,1,pontiac phoenix
373,24.0,4,140.0,92,2865,16.4,82,1,ford fairmont futura
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl
375,36.0,4,105.0,74,1980,15.3,82,2,volkswagen rabbit l
376,37.0,4,91.0,68,2025,18.2,82,3,mazda glc custom l
377,31.0,4,91.0,68,1970,17.6,82,3,mazda glc custom
378,38.0,4,105.0,63,2125,14.7,82,1,plymouth horizon miser
379,36.0,4,98.0,70,2125,17.3,82,1,mercury lynx l
380,36.0,4,120.0,88,2160,14.5,82,3,nissan stanza xe
381,36.0,4,107.0,75,2205,14.5,82,3,honda accord
382,34.0,4,108.0,70,2245,16.9,82,3,toyota corolla
383,38.0,4,91.0,67,1965,15.0,82,3,honda civic
384,32.0,4,91.0,67,1965,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67,1995,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110,2945,16.4,82,1,buick century limited
387,38.0,6,262.0,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [5]:
dataset.corr()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000

In [7]:
feature = dataset['displacement']
target_var= dataset['cylinders']

In [8]:
feature

0      307.0
1      350.0
2      318.0
3      304.0
4      302.0
5      429.0
6      454.0
7      440.0
8      455.0
9      390.0
10     383.0
11     340.0
12     400.0
13     455.0
14     113.0
15     198.0
16     199.0
17     200.0
18      97.0
19      97.0
20     110.0
21     107.0
22     104.0
23     121.0
24     199.0
25     360.0
26     307.0
27     318.0
28     304.0
29      97.0
       ...
368    112.0
369    112.0
370    112.0
371    135.0
372    151.0
373    140.0
374    151.0
375    105.0
376     91.0
377     91.0
378    105.0
379     98.0
380    120.0
381    107.0
382    108.0
383     91.0
384     91.0
385     91.0
386    181.0
387    262.0
388    156.0
389    232.0
390    144.0
391    135.0
392    151.0
393    140.0
394     97.0
395    135.0
396    120.0
397    119.0
Name: displacement, Length: 398, dtype: float64

In [9]:
target_var

0      8
1      8
2      8
3      8
4      8
5      8
6      8
7      8
8      8
9      8
10     8
11     8
12     8
13     8
14     4
15     6
16     6
17     6
18     4
19     4
20     4
21     4
22     4
23     4
24     6
25     8
26     8
27     8
28     8
29     4
      ..
368    4
369    4
370    4
371    4
372    4
373    4
374    4
375    4
376    4
377    4
378    4
379    4
380    4
381    4
382    4
383    4
384    4
385    4
386    6
387    6
388    4
389    6
390    4
391    4
392    4
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64